//
// HashMap.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A hashmap (array of key/value pairs) */
public typealias HashMap = [HashSet]
