swagger: "2.0"
info:
  description: "A fileserver API"
  version: "0.0.1"
  title: "go-fileserver"
  
host: localhost:8443
basePath: "/"
schemes: 
  - "https"
paths:
  /{path}:
    get:
      tags:
        - "path"
      summary: "List the contents of a directory or retrieve file"
      parameters:
        - in: "path"
          name: "path"
          description: "Directory to list or file to return"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
        401:
          description: "unauthorized"
        404:
          description: "path not found"
        500:
          description: "unknown error"
          schema:
            $ref: "#/definitions/500Error"
      security:
        - bearerAuth: []
  /auth:
    get:
      tags:
        - "auth"
      summary: "List all pending authorizations"
      produces:
        - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
        403:
          description: "Unauthorized for request"
      security:
        - bearerAuth: []
    post:
      tags:
        - "auth"
      summary: "Requests authorization"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: "key"
          description: "key to stage for access"
          schema:
            type: "object"
            properties:
              key:
                type: "string"
      responses:
        202:
          description: "successful operation, request will be processed later"
    put:
      tags:
        - "auth"
      summary: "Activiate a pending authorization"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: "key"
          description: "key to add for access"
          schema:
            type: "object"
            properties:
              key:
                type: "string"
      responses:
        200:
          description: "successful operation"
        403:
          description: "Unauthorized for request"
      security:
        - bearerAuth: []
    delete:
      tags:
        - "auth"
      summary: "Delete an authorization (pending or allowed)"
      parameters:
        - in: "query"
          name: "key"
          type: "string"
          description: "delete a key from access"
      responses:
        200:
          description: "successful operation"
        403:
          description: "Unauthorized for request"
      security:
        - bearerAuth: []
definitions:
  500Error:
    description: "internal server error"
    type: "object"
    properties:
      error: 
        type: "string"
securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
