# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FileView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FileView

  target 'FileViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FileViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire', '~> 4.7'
end
